<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="AvailableTestsServiceDefinitions" targetNamespace="http://webtest.skillcheck.com" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://www.w3.org/2001/XMLSchema" xmlns:s2="http://webtest.skillcheck.com" xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/">
  <s0:types/>
  <s0:message name="GetAvailableTests">
    <s0:part name="clientAccountID" type="s1:string"/>
    <s0:part name="clientUsername" type="s1:string"/>
    <s0:part name="clientPassword" type="s1:string"/>
  </s0:message>
  <s0:message name="GetAvailableTestsResponse">
    <s0:part name="return" type="s1:string"/>
  </s0:message>
  <s0:portType name="AvailableTests">
    <s0:operation name="GetAvailableTests" parameterOrder="clientAccountID clientUsername clientPassword">
      <s0:input message="s2:GetAvailableTests"/>
      <s0:output message="s2:GetAvailableTestsResponse"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="AvailableTestsServiceSoapBinding" type="s2:AvailableTests">
    <s3:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <s0:operation name="GetAvailableTests">
      <s3:operation soapAction="" style="rpc"/>
      <s0:input>
        <s3:body namespace="http://webtest.skillcheck.com" parts="clientAccountID clientUsername clientPassword" use="literal"/>
      </s0:input>
      <s0:output>
        <s3:body namespace="http://webtest.skillcheck.com" parts="return" use="literal"/>
      </s0:output>
    </s0:operation>
  </s0:binding>
  <s0:service name="AvailableTestsService">
    <s0:port binding="s2:AvailableTestsServiceSoapBinding" name="AvailableTestsSoapPort">
      <s3:address location="http://localhost:8080/onlinetesting/services/AvailableTests"/>
    </s0:port>
  </s0:service>
</s0:definitions>