<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="PasswordAssessmentIntegrationServiceDefinitions" targetNamespace="http://webtest.skillcheck.com" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://www.w3.org/2001/XMLSchema" xmlns:s2="http://webtest.skillcheck.com" xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/">
  <s0:types/>
  <s0:message name="retrieveDetailedResults">
    <s0:part name="ASR" type="s1:string"/>
  </s0:message>
  <s0:message name="retrieveDetailedResultsResponse">
    <s0:part name="return" type="s1:string"/>
  </s0:message>
  <s0:message name="InitiateCandidateTest">
    <s0:part name="AOR" type="s1:string"/>
  </s0:message>
  <s0:message name="InitiateCandidateTestResponse">
    <s0:part name="return" type="s1:string"/>
  </s0:message>
  <s0:portType name="PasswordAssessmentIntegration">
    <s0:operation name="retrieveDetailedResults" parameterOrder="ASR">
      <s0:input message="s2:retrieveDetailedResults"/>
      <s0:output message="s2:retrieveDetailedResultsResponse"/>
    </s0:operation>
    <s0:operation name="InitiateCandidateTest" parameterOrder="AOR">
      <s0:input message="s2:InitiateCandidateTest"/>
      <s0:output message="s2:InitiateCandidateTestResponse"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="PasswordAssessmentIntegrationServiceSoapBinding" type="s2:PasswordAssessmentIntegration">
    <s3:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <s0:operation name="retrieveDetailedResults">
      <s3:operation soapAction="" style="rpc"/>
      <s0:input>
        <s3:body namespace="http://webtest.skillcheck.com" parts="ASR" use="literal"/>
      </s0:input>
      <s0:output>
        <s3:body namespace="http://webtest.skillcheck.com" parts="return" use="literal"/>
      </s0:output>
    </s0:operation>
    <s0:operation name="InitiateCandidateTest">
      <s3:operation soapAction="" style="rpc"/>
      <s0:input>
        <s3:body namespace="http://webtest.skillcheck.com" parts="AOR" use="literal"/>
      </s0:input>
      <s0:output>
        <s3:body namespace="http://webtest.skillcheck.com" parts="return" use="literal"/>
      </s0:output>
    </s0:operation>
  </s0:binding>
  <s0:service name="PasswordAssessmentIntegrationService">
    <s0:port binding="s2:PasswordAssessmentIntegrationServiceSoapBinding" name="PasswordAssessmentIntegrationSoapPort">
      <s3:address location="http://localhost:8080/onlinetesting/services/PasswordAssessmentIntegration"/>
    </s0:port>
  </s0:service>
</s0:definitions>