
package com.skillcheck.web_management.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApiService", targetNamespace = "http://webtest.skillcheck.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ApiService {


    /**
     * 
     * @param username
     * @param accountId
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String startSession(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "accountId", partName = "accountId")
        String accountId);

    /**
     * 
     * @param pKey
     * @param docHRXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getETicket(
        @WebParam(name = "pKey", partName = "pKey")
        String pKey,
        @WebParam(name = "docHRXML", partName = "docHRXML")
        String docHRXML);

}
