
package com.skillcheck.web_management.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LicenseActivationService", targetNamespace = "http://webtest.skillcheck.com", wsdlLocation = "http://localhost:8080/onlinetesting/services/LicenseActivation?wsdl")
public class LicenseActivationService
    extends Service
{

    private final static URL LICENSEACTIVATIONSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/onlinetesting/services/LicenseActivation?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LICENSEACTIVATIONSERVICE_WSDL_LOCATION = url;
    }

    public LicenseActivationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicenseActivationService() {
        super(LICENSEACTIVATIONSERVICE_WSDL_LOCATION, new QName("http://webtest.skillcheck.com", "LicenseActivationService"));
    }

    /**
     * 
     * @return
     *     returns LicenseActivation
     */
    @WebEndpoint(name = "LicenseActivationSoapPort")
    public LicenseActivation getLicenseActivationSoapPort() {
        return (LicenseActivation)super.getPort(new QName("http://webtest.skillcheck.com", "LicenseActivationSoapPort"), LicenseActivation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LicenseActivation
     */
    @WebEndpoint(name = "LicenseActivationSoapPort")
    public LicenseActivation getLicenseActivationSoapPort(WebServiceFeature... features) {
        return (LicenseActivation)super.getPort(new QName("http://webtest.skillcheck.com", "LicenseActivationSoapPort"), LicenseActivation.class, features);
    }

}
