package com.skillcheck.web_management.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StatisticsService", targetNamespace = "http://webtest.skillcheck.com", wsdlLocation = "http://localhost:8080/onlinetesting/services/Statistics?wsdl")
public class StatisticsService
    extends Service
{

    private final static URL STATISTICSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7001/onlinetesting/services/Statistics?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        STATISTICSSERVICE_WSDL_LOCATION = url;
    }

    public StatisticsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatisticsService() {
        super(STATISTICSSERVICE_WSDL_LOCATION, new QName("http://webtest.skillcheck.com", "StatisticsService"));
    }

    /**
     * 
     * @return
     *     returns Statistics
     */
    @WebEndpoint(name = "StatisticsSoapPort")
    public Statistics getStatisticsSoapPort() {
        return (Statistics)super.getPort(new QName("http://webtest.skillcheck.com", "StatisticsSoapPort"), Statistics.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Statistics
     */
    @WebEndpoint(name = "StatisticsSoapPort")
    public Statistics getStatisticsSoapPort(WebServiceFeature... features) {
        return (Statistics)super.getPort(new QName("http://webtest.skillcheck.com", "StatisticsSoapPort"), Statistics.class, features);
    }

}
