
package alokamMTOMClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MtomService", targetNamespace = "http://example.org", wsdlLocation = "http://localhost:9090/test/alokam/MTOMImpl?wsdl")
public class MtomService
    extends Service
{

    private final static URL MTOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTOMSERVICE_EXCEPTION;
    private final static QName MTOMSERVICE_QNAME = new QName("http://example.org", "MtomService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/test/alokam/MTOMImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTOMSERVICE_WSDL_LOCATION = url;
        MTOMSERVICE_EXCEPTION = e;
    }

    public MtomService() {
        super(__getWsdlLocation(), MTOMSERVICE_QNAME);
    }

    public MtomService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTOMSERVICE_QNAME);
    }

    public MtomService(URL wsdlLocation) {
        super(wsdlLocation, MTOMSERVICE_QNAME);
    }

    public MtomService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTOMSERVICE_QNAME);
    }

    public MtomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MtomService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtomPortType
     */
    @WebEndpoint(name = "MtomPortTypePort")
    public MtomPortType getMtomPortTypePort() {
        return super.getPort(new QName("http://example.org", "MtomPortTypePort"), MtomPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MtomPortType
     */
    @WebEndpoint(name = "MtomPortTypePort")
    public MtomPortType getMtomPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org", "MtomPortTypePort"), MtomPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTOMSERVICE_EXCEPTION!= null) {
            throw MTOMSERVICE_EXCEPTION;
        }
        return MTOMSERVICE_WSDL_LOCATION;
    }

}
