
package sampleClient;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice", className = "sampleClient.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice", className = "sampleClient.HelloResponse")
    public void hello();

}
