
package BullhornClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiService", targetNamespace = "http://apiservice.bullhorn.com/", wsdlLocation = "file:/D:/bullhorn/XSD/Bullhorn.wsdl")
public class ApiService_Service
    extends Service
{

    private final static URL APISERVICE_WSDL_LOCATION;
    private final static WebServiceException APISERVICE_EXCEPTION;
    private final static QName APISERVICE_QNAME = new QName("http://apiservice.bullhorn.com/", "ApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/bullhorn/XSD/Bullhorn.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APISERVICE_WSDL_LOCATION = url;
        APISERVICE_EXCEPTION = e;
    }

    public ApiService_Service() {
        super(__getWsdlLocation(), APISERVICE_QNAME);
    }

    public ApiService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), APISERVICE_QNAME);
    }

    public ApiService_Service(URL wsdlLocation) {
        super(wsdlLocation, APISERVICE_QNAME);
    }

    public ApiService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APISERVICE_QNAME);
    }

    public ApiService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ApiService
     */
    @WebEndpoint(name = "ApiServicePort")
    public ApiService getApiServicePort() {
        return super.getPort(new QName("http://apiservice.bullhorn.com/", "ApiServicePort"), ApiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiService
     */
    @WebEndpoint(name = "ApiServicePort")
    public ApiService getApiServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://apiservice.bullhorn.com/", "ApiServicePort"), ApiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APISERVICE_EXCEPTION!= null) {
            throw APISERVICE_EXCEPTION;
        }
        return APISERVICE_WSDL_LOCATION;
    }

}
