
package com.skillcheck.web_management.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ApiService", targetNamespace = "http://webtest.skillcheck.com", wsdlLocation = "file:/D:/Personal/JaxwsSample1/web/WEB-INF/wsdl/ApiService.wsdl")
public class ApiService_Service
    extends Service
{

    private final static URL APISERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Personal/JaxwsSample1/web/WEB-INF/wsdl/ApiService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        APISERVICE_WSDL_LOCATION = url;
    }

    public ApiService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiService_Service() {
        super(APISERVICE_WSDL_LOCATION, new QName("http://webtest.skillcheck.com", "ApiService"));
    }

    /**
     * 
     * @return
     *     returns ApiService
     */
    @WebEndpoint(name = "ApiServiceSoapPort")
    public ApiService getApiServiceSoapPort() {
        return (ApiService)super.getPort(new QName("http://webtest.skillcheck.com", "ApiServiceSoapPort"), ApiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiService
     */
    @WebEndpoint(name = "ApiServiceSoapPort")
    public ApiService getApiServiceSoapPort(WebServiceFeature... features) {
        return (ApiService)super.getPort(new QName("http://webtest.skillcheck.com", "ApiServiceSoapPort"), ApiService.class, features);
    }

}
