
package com.skillcheck.web_management.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AvailableTestsService", targetNamespace = "http://webtest.skillcheck.com", wsdlLocation = "file:/D:/Personal/JaxwsSample1/web/WEB-INF/wsdl/AvailableTestsService.wsdl")
public class AvailableTestsService
    extends Service
{

    private final static URL AVAILABLETESTSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Personal/JaxwsSample1/web/WEB-INF/wsdl/AvailableTestsService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        AVAILABLETESTSSERVICE_WSDL_LOCATION = url;
    }

    public AvailableTestsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AvailableTestsService() {
        super(AVAILABLETESTSSERVICE_WSDL_LOCATION, new QName("http://webtest.skillcheck.com", "AvailableTestsService"));
    }

    /**
     * 
     * @return
     *     returns AvailableTests
     */
    @WebEndpoint(name = "AvailableTestsSoapPort")
    public AvailableTests getAvailableTestsSoapPort() {
        return (AvailableTests)super.getPort(new QName("http://webtest.skillcheck.com", "AvailableTestsSoapPort"), AvailableTests.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AvailableTests
     */
    @WebEndpoint(name = "AvailableTestsSoapPort")
    public AvailableTests getAvailableTestsSoapPort(WebServiceFeature... features) {
        return (AvailableTests)super.getPort(new QName("http://webtest.skillcheck.com", "AvailableTestsSoapPort"), AvailableTests.class, features);
    }

}
