
package com.skillcheck.web_management.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AvailableTests", targetNamespace = "http://webtest.skillcheck.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AvailableTests {


    /**
     * 
     * @param clientAccountID
     * @param clientPassword
     * @param clientUsername
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAvailableTests")
    @WebResult(partName = "return")
    public String getAvailableTests(
        @WebParam(name = "clientAccountID", partName = "clientAccountID")
        String clientAccountID,
        @WebParam(name = "clientUsername", partName = "clientUsername")
        String clientUsername,
        @WebParam(name = "clientPassword", partName = "clientPassword")
        String clientPassword);

}
