
package com.skillcheck.web_management.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LicenseActivation", targetNamespace = "http://webtest.skillcheck.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface LicenseActivation {


    /**
     * 
     * @param password
     * @param username
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String licenseStatus(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "invoice", partName = "invoice")
        String invoice);

    /**
     * 
     * @param password
     * @param requestCode
     * @param username
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String activateLicense(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "requestCode", partName = "requestCode")
        String requestCode,
        @WebParam(name = "IP", partName = "IP")
        String ip);

    /**
     * 
     * @param password
     * @param username
     * @param ip
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String resetLicense(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "invoice", partName = "invoice")
        String invoice,
        @WebParam(name = "IP", partName = "IP")
        String ip);

    /**
     * 
     * @param password
     * @param username
     * @param ip
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String createLicense(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "invoice", partName = "invoice")
        String invoice,
        @WebParam(name = "IP", partName = "IP")
        String ip);

    /**
     * 
     * @param password
     * @param username
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String isLicenseAvailable(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "invoice", partName = "invoice")
        String invoice);

    /**
     * 
     * @param password
     * @param username
     * @param ip
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String disableLicense(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "invoice", partName = "invoice")
        String invoice,
        @WebParam(name = "IP", partName = "IP")
        String ip);

}
