
package com.skillcheck.web_management.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PasswordAssessmentIntegration", targetNamespace = "http://webtest.skillcheck.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PasswordAssessmentIntegration {


    /**
     * 
     * @param asr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String retrieveDetailedResults(
        @WebParam(name = "ASR", partName = "ASR")
        String asr);

    /**
     * 
     * @param aor
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InitiateCandidateTest")
    @WebResult(partName = "return")
    public String initiateCandidateTest(
        @WebParam(name = "AOR", partName = "AOR")
        String aor);

}
