
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloImplService", targetNamespace = "http://asyanchronusWEBService/", wsdlLocation = "http://localhost:9090/test/services/HelloService?wsdl")
public class HelloImplService
    extends Service
{

    private final static URL HELLOIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/venu/HelloService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HELLOIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloImplService() {
        super(HELLOIMPLSERVICE_WSDL_LOCATION, new QName("http://asyanchronusWEBService/", "HelloImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloImpl
     */
    @WebEndpoint(name = "HelloImplPort")
    public HelloImpl getHelloImplPort() {
        return (HelloImpl)super.getPort(new QName("http://asyanchronusWEBService/", "HelloImplPort"), HelloImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloImpl
     */
    @WebEndpoint(name = "HelloImplPort")
    public HelloImpl getHelloImplPort(WebServiceFeature... features) {
        return (HelloImpl)super.getPort(new QName("http://asyanchronusWEBService/", "HelloImplPort"), HelloImpl.class, features);
    }

}
