
package mypackage;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloImpl", targetNamespace = "http://asyanchronusWEBService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://asyanchronusWEBService/", className = "mypackage.SayHello")
    @Action(input = "http://asyanchronusWEBService/HelloImpl/sayHello")
    public void sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "callbackMessage", targetNamespace = "http://asyanchronusWEBService/", className = "mypackage.CallbackMessage")
    @Action(input = "http://asyanchronusWEBService/HelloImpl/callbackMessage")
    public void callbackMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
